In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print(f"Shape: {arr.shape}")
print("Data Type:",arr.dtype)
print("Size:",arr.size)

Shape: (5,)
Data Type: int64
Size: 5


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition:",a+b)
print("Multiplication:",a*b)
print("Dot Product:", np.dot(a,b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
print ("Matrix:",matrix.shape)
print("Dimensions:",matrix.ndim)
print(matrix)

Matrix: (2, 3)
Dimensions: 2
[[1 2 3]
 [4 5 6]]


In [6]:
print("Element at [0,1]:",matrix[0,1])
print("Element row:",matrix[0,:])
print("Element column:",matrix[:,1])

Element at [0,1]: 2
Element row: [1 2 3]
Element column: [2 5]


In [7]:
print("Matrix *2 :\n",matrix*2)
print("Matrix+10 :\n",matrix + 10)
print(matrix.sum())
print(matrix.sum(axis=1))
print(matrix.sum(axis=0))

Matrix *2 :
 [[ 2  4  6]
 [ 8 10 12]]
Matrix+10 :
 [[11 12 13]
 [14 15 16]]
21
[ 6 15]
[5 7 9]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[10,11],[9,12]])
print(np.dot(a,b))
print(np.dot(a,b).shape)

[[ 54  66]
 [132 159]]
(2, 2)
