In [1]:
import numpy as np

word1 = np.array([1.0,0.5,0.2])
word2 = np.array([0.1,0.8,0.9])
word3 = np.array([1.1,0.4,0.3])

In [2]:
sim_word1_word2 = np.dot(word1,word2)
sim_word1_word3 = np.dot(word1,word3)

print("word 2 is more similar to word 1" if sim_word1_word2 > sim_word1_word3 else "word3 is more similar to word 1")

word3 is more similar to word 1


In [3]:
norm_word1 = word1 / np.linalg.norm(word1)
norm_word2 = word2 / np.linalg.norm(word2)
norm_word3 = word3 / np.linalg.norm(word3)

print("Normalised word 1:",norm_word1)
print("Cosine similarity word 1-word 3:",np.dot(norm_word1,norm_word3))

Normalised word 1: [0.88045091 0.44022545 0.17609018]
Cosine similarity word 1-word 3: 0.9909862423925143


In [4]:
word_matrix = np.stack([word1, word2, word3])
print("Word matrix:\n",word_matrix)
similarities = np.dot(word_matrix, word_matrix.T)
print("All similarities:\n",similarities)

Word matrix:
 [[1.  0.5 0.2]
 [0.1 0.8 0.9]
 [1.1 0.4 0.3]]
All similarities:
 [[1.29 0.68 1.36]
 [0.68 1.46 0.7 ]
 [1.36 0.7  1.46]]
